---
title: ESMA 6835 Computing with R
header-includes: \usepackage{color}
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

<style>
table, th, td { text-align:right; }
th, td {padding: 10px;}
</style>

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/teaching/Resma3/Resma3.RData"))
library(knitr)
opts_chunk$set(fig.width=6, fig.align = "center", 
      out.width = "70%", warning=FALSE, message=FALSE)
library(ggplot2)
library(grid)
library(stringr)
```
`r hl()$basefontsize()`

[Entire class as pdf (10MB)](Computing-with-R.pdf)  
[Syllabus](syl.html)  
[Assignments](assign.html)  
[Resma3.RData](http://academic.uprm.edu/wrolke/Resma3/Resma3.RData?Ver 3.0) (Ver 3.0)

#1  Getting Started

1.1&nbsp;  [Installation and Updating](install.html)  
1.2&nbsp;  [R Markdown, HTML and Latex](rmark.html)  
1.2&nbsp;  [History, Basic Usage](general.stuff.html)  

#2  Base R

2.1&nbsp; [Data types](datatypes.html)  
2.2&nbsp; [Vectors, matrices, dataframes and lists](dataformats.html)  
2.3&nbsp; [Generating objects](generate.vectors.html)  
2.4&nbsp; [Subsetting](subset.html)  
2.5&nbsp; [Random Numbers](random.numbers.html)  
2.6&nbsp; [Writing functions, Programming](write.functions.html)  
2.7&nbsp; [Object-Oriented Programming](object.oriented.Rmd)  
2.8&nbsp; [Vector arithmetic, Linear Algebra](vector.arithmetic.html)   
2.9&nbsp; [Character manipulation](character.html)  
2.10 [Data input/output, transfering R objects](io.html)   
2.11 [Graphs](graphs.html)  
2.12 [Model Notation](model.notation.html)  
2.13 [Numerical Methods](numerical.methods.html)  
2.14 [Environments, libraries](environments.html)    
2.15 [Costumizing R: .First, .Rprofile, Dropbox](customization.html)  

#3  Extending R, Packages

3.1&nbsp; [Graphics with ggplot2](ggplot2.html)  
3.2&nbsp; [C++ with Rcpp](rcpp.html)  
3.3&nbsp; [Parallel and gpu computing](parallel.html)  
3.4&nbsp; [Input/Output revisited](io1.hmtl)  
3.5&nbsp; [The pipe, dplyr, tibbles, tidyverse](pipe.html)  
3.6&nbsp; [Character manipulation with strngr](character1.html)  
3.7&nbsp; [Dates with lubridate](dates.html)  
3.8&nbsp; [Factors with forcats](forcats.html)  
3.9&nbsp; [Iteration with purrr](purrr.html)  
3.10  [Interactive Apps with shiny](shiny.html)  
3.11  [Version Control and Collaboration with github](github.html)  


#4  Statistics with R

4.1  [Estimation](estimation.html)  
4.2  [The Bootstrap](bootstrap.html)  
4.3  [Curve Fitting / Regression](curve.fitting.html)  
4.4  [Classification](classification.html)  
4.5  [Bayesian Analysis](bayes.html)  
4.6  ??


