---
title: Syllabus
                 \usepackage{float}
header-includes: \usepackage{color} 
output:
  html_document: default
  pdf_document:
    fig_caption: no
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/teaching/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`

Professor: Dr. Wolfgang Rolke  
Time and Place:  
Tuesday, Thursday 12:30 - 1:45pm  SH105

### Reading List:

There are literally 100s of books about R, with new ones coming out almost every week. Here are some that I found useful:

[Learning R](https://www.amazon.com/Learning-R-Richard-Cotton/dp/1449357105/ref=dp_rm_title_1)

[Introduction to Data Science with R](http://shop.oreilly.com/product/0636920034834.do)

[R Cookbook](https://www.amazon.com/Cookbook-OReilly-Cookbooks-Paul-Teetor/dp/0596809158/ref=dp_rm_title_0)

[Advanced R](https://englianhu.files.wordpress.com/2016/05/advanced-r.pdf)

### Office hours

Tuesday, Thursday 12:00-12:30pm OF407  
Tuesday, Thursday 1:45-3:15pm OF407 (by appointment)  
Wednesday  1:00-3:00pm via email   
email: wolfgang[dot]rolke[at]upr[dot]edu   

when you send me an email `r hl()$fontcolor("ALWAYS")` start the subject line with <font color="red">ESMA 6835</font>

### Grading:

1.  Homework: 50%  
2.  Midterm 25%  
3.  Final 25%  

### Submit your work

all homeworks and exams have to be done using RMarkdown and have to be submitted via Dropbox. You will be sent an invitation to join Dropbox soon (if you are not already a user). A little while later you will receive an email with an invitation to share a Dropbox folder with me. 

From then on anytime you put something in this folder I will immediately have it in mine as well. So when you are ready to submit your homework simply drop the file into the folder. 
